#!/bin/bash
directory=$(pwd);
clear;
echo '1) Создать папки и файлы';
echo '2) Удалить папки и файлы';
echo '0) Ничего не делать';
printf 'Введите значение: ';
read -n 1 Z
clear;
case $Z in
0)
echo 'Выход';
;;
1)
printf 'Введите образ имени папок: ';
read pattern1
len=${#pattern1};
for (( i=0; i<len; i++)); do
    if [[ ${pattern1:$i:1} == '/' ]] 
    then
        echo 'ERROR!!111 /';
        exit 1;
    fi
done
printf 'Введите образ имени файлов: ';
read pattern2
len=${#pattern2};
for (( i=0; i<len; i++)); do
    if [[ ${pattern2:$i:1} == '/' ]] 
    then
        echo 'ERROR!!111 /';
        exit 1;
    fi
done
printf 'Введите колтчество папок: '
read A;
if [ $A -eq $A 2> /dev/null ];
then
echo 'Успех';
elif [ $A -lt 1 ];
then
clear;
echo 'Число меньше 1';
exit 1;
else
clear;
echo 'Введены буквы';
exit 1;
fi
printf 'Введите колтчество файлов: '
read B;
if [ $B -eq $B 2> /dev/null ];
then
echo 'Успех';
elif [ $A -lt 0 ];
then
clear;
echo 'Число меньше 0';
exit 1;
else
clear;
echo 'Введены буквы';
exit 1;
fi
cols=$(tput cols);
cols=$(( $cols-2 ))
if [[ $B -eq 0 ]]
then
    C=$(( $A ))
else
    C=$(( $A*$B ));
fi
clear;
tput cup 0 0;
D=0;
Eold=-1;
tmpp=0;
for (( i=1; i<=$A; i++ )); do
    mkdir "$directory/DIR/$pattern1$i";
    if [[ $B -ne 0 ]];
    then
        for (( j=1; j<=$B; j++ )); do
            E=$(($D*$cols/$C+1));
            Y=$(($cols-$E));
            for (( tmpp; tmpp==0; tmpp++ )); do
                tput cup 0 0;
                printf '[';
                for (( k=1; k<=$E; k++ )); do
                    printf '#';
                done
                for (( k=1; k<=$Y; k++ )); do
                    printf '_';
                done
                printf ']';
                Eold=$E;
            done
            for (( tmpp; tmpp==5; tmpp++ )); do
                if [ $E -gt $Eold ];
                then
                    razn=$((1+$E-$Eold));
                    pos=$(($Eold));
                    tput cup 0 $pos;
                    for (( k=1; k<=$razn; k++ )); do
                        printf '#';
                    done
                    Eold=$E;
                fi
            done
            tmpp=5;
            D=$(($D+1));
            touch "$directory/DIR/$pattern1$i/$pattern2$j";
        done
    else
        D=$(($D+1));
    fi
done
echo ;
echo success;
;;
2)
find $directory/DIR/ -name "*" -exec rm {} \; 2> /dev/null;
find $directory/DIR/ -name "*" -exec rmdir {} \; 2> /dev/null;
echo success;
;;
*)
echo 'Неправильный выбор'
;;
esac